.PHONY: clean setup destroy
clean:
	rm inputs/*.txt
	rm log/*.txt
	rm outputs/*/*.txt

setup:
	mkdir inputs
	mkdir log
	mkdir outputs
	mkdir outputs/xh
	mkdir outputs/partner

destroy:
	rm -rf inputs
	rm -rf log
	rm -rf outputs